//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rainbow6_ReplayHandler {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rainbow6_ReplayHandler.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 《彩虹六号：围攻》不在运行。请先打开游戏，然后点击确认。这将帮助我们定位游戏安装位置。 的本地化字符串。
        /// </summary>
        internal static string GAME_INSTANCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GAME_INSTANCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到游戏 的本地化字符串。
        /// </summary>
        internal static string GAME_INSTANCE_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("GAME_INSTANCE_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 占点 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_AREA {
            get {
                return ResourceManager.GetString("GAMEMODE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炸弹 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_BOMB {
            get {
                return ResourceManager.GetString("GAMEMODE_BOMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人质 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_HOSTAGE {
            get {
                return ResourceManager.GetString("GAMEMODE_HOSTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_UNKNOWN {
            get {
                return ResourceManager.GetString("GAMEMODE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_CUSTOM_LOCAL {
            get {
                return ResourceManager.GetString("GAMETYPE_CUSTOM_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_CUSTOM_ONLINE {
            get {
                return ResourceManager.GetString("GAMETYPE_CUSTOM_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_QUICKMATCH {
            get {
                return ResourceManager.GetString("GAMETYPE_QUICKMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排位 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_RANKED {
            get {
                return ResourceManager.GetString("GAMETYPE_RANKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("GAMETYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非排 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_UNRANKED {
            get {
                return ResourceManager.GetString("GAMETYPE_UNRANKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行 的本地化字符串。
        /// </summary>
        internal static string MAP_BANK {
            get {
                return ResourceManager.GetString("MAP_BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大学 的本地化字符串。
        /// </summary>
        internal static string MAP_BARTLETT_U {
            get {
                return ResourceManager.GetString("MAP_BARTLETT_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边境 的本地化字符串。
        /// </summary>
        internal static string MAP_BORDER {
            get {
                return ResourceManager.GetString("MAP_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 木屋 的本地化字符串。
        /// </summary>
        internal static string MAP_CHALET {
            get {
                return ResourceManager.GetString("MAP_CHALET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俱乐部 的本地化字符串。
        /// </summary>
        internal static string MAP_CLUB_HOUSE {
            get {
                return ResourceManager.GetString("MAP_CLUB_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海岸线 的本地化字符串。
        /// </summary>
        internal static string MAP_COASTLINE {
            get {
                return ResourceManager.GetString("MAP_COASTLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使馆 的本地化字符串。
        /// </summary>
        internal static string MAP_CONSULATE {
            get {
                return ResourceManager.GetString("MAP_CONSULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翡翠原 的本地化字符串。
        /// </summary>
        internal static string MAP_EMERALD_PLAINS {
            get {
                return ResourceManager.GetString("MAP_EMERALD_PLAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贫民窟 的本地化字符串。
        /// </summary>
        internal static string MAP_FAVELA {
            get {
                return ResourceManager.GetString("MAP_FAVELA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堡垒 的本地化字符串。
        /// </summary>
        internal static string MAP_FORTRESS {
            get {
                return ResourceManager.GetString("MAP_FORTRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赫里福 的本地化字符串。
        /// </summary>
        internal static string MAP_HEREFORD_BASE {
            get {
                return ResourceManager.GetString("MAP_HEREFORD_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 豪宅 的本地化字符串。
        /// </summary>
        internal static string MAP_HOUSE {
            get {
                return ResourceManager.GetString("MAP_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 咖啡馆 的本地化字符串。
        /// </summary>
        internal static string MAP_KAFE_DOSTOYEVSKY {
            get {
                return ResourceManager.GetString("MAP_KAFE_DOSTOYEVSKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运河 的本地化字符串。
        /// </summary>
        internal static string MAP_KANAL {
            get {
                return ResourceManager.GetString("MAP_KANAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永夜安港 的本地化字符串。
        /// </summary>
        internal static string MAP_NIGHTHAVEN_LABS {
            get {
                return ResourceManager.GetString("MAP_NIGHTHAVEN_LABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄勒冈 的本地化字符串。
        /// </summary>
        internal static string MAP_OREGON {
            get {
                return ResourceManager.GetString("MAP_OREGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荒漠 的本地化字符串。
        /// </summary>
        internal static string MAP_OUTBACK {
            get {
                return ResourceManager.GetString("MAP_OUTBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞机 的本地化字符串。
        /// </summary>
        internal static string MAP_PRESIDENTIAL_PLANE {
            get {
                return ResourceManager.GetString("MAP_PRESIDENTIAL_PLANE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摩天大楼 的本地化字符串。
        /// </summary>
        internal static string MAP_SKYSCRAPER {
            get {
                return ResourceManager.GetString("MAP_SKYSCRAPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B号 的本地化字符串。
        /// </summary>
        internal static string MAP_STADIUM_BRAVO {
            get {
                return ResourceManager.GetString("MAP_STADIUM_BRAVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题公园 的本地化字符串。
        /// </summary>
        internal static string MAP_THEME_PARK {
            get {
                return ResourceManager.GetString("MAP_THEME_PARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 塔楼 的本地化字符串。
        /// </summary>
        internal static string MAP_TOWER {
            get {
                return ResourceManager.GetString("MAP_TOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string MAP_UNKNOWN {
            get {
                return ResourceManager.GetString("MAP_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别墅 的本地化字符串。
        /// </summary>
        internal static string MAP_VILLA {
            get {
                return ResourceManager.GetString("MAP_VILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游轮 的本地化字符串。
        /// </summary>
        internal static string MAP_YACHT {
            get {
                return ResourceManager.GetString("MAP_YACHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个后台任务遇到了错误。不用担心，这一般不会影响其它功能运行。 的本地化字符串。
        /// </summary>
        internal static string TASK_EXCEPTION {
            get {
                return ResourceManager.GetString("TASK_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台任务出错 的本地化字符串。
        /// </summary>
        internal static string TASK_EXCEPTION_TITLE {
            get {
                return ResourceManager.GetString("TASK_EXCEPTION_TITLE", resourceCulture);
            }
        }
    }
}
