//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rainbow6_ReplayHandler {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rainbow6_ReplayHandler.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 RainbowSix:Seige is not running. Start the game and click OK. By doing this, we will be able to locate the game. 的本地化字符串。
        /// </summary>
        internal static string GAME_INSTANCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GAME_INSTANCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game not cound 的本地化字符串。
        /// </summary>
        internal static string GAME_INSTANCE_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("GAME_INSTANCE_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secure Area 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_AREA {
            get {
                return ResourceManager.GetString("GAMEMODE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bomb 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_BOMB {
            get {
                return ResourceManager.GetString("GAMEMODE_BOMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hostage 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_HOSTAGE {
            get {
                return ResourceManager.GetString("GAMEMODE_HOSTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string GAMEMODE_UNKNOWN {
            get {
                return ResourceManager.GetString("GAMEMODE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_CUSTOM_LOCAL {
            get {
                return ResourceManager.GetString("GAMETYPE_CUSTOM_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_CUSTOM_ONLINE {
            get {
                return ResourceManager.GetString("GAMETYPE_CUSTOM_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_QUICKMATCH {
            get {
                return ResourceManager.GetString("GAMETYPE_QUICKMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranked 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_RANKED {
            get {
                return ResourceManager.GetString("GAMETYPE_RANKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("GAMETYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unranked 的本地化字符串。
        /// </summary>
        internal static string GAMETYPE_UNRANKED {
            get {
                return ResourceManager.GetString("GAMETYPE_UNRANKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bank	 的本地化字符串。
        /// </summary>
        internal static string MAP_BANK {
            get {
                return ResourceManager.GetString("MAP_BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bartlett University 的本地化字符串。
        /// </summary>
        internal static string MAP_BARTLETT_U {
            get {
                return ResourceManager.GetString("MAP_BARTLETT_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border	 的本地化字符串。
        /// </summary>
        internal static string MAP_BORDER {
            get {
                return ResourceManager.GetString("MAP_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chalet	 的本地化字符串。
        /// </summary>
        internal static string MAP_CHALET {
            get {
                return ResourceManager.GetString("MAP_CHALET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Club	 的本地化字符串。
        /// </summary>
        internal static string MAP_CLUB_HOUSE {
            get {
                return ResourceManager.GetString("MAP_CLUB_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coast Line 的本地化字符串。
        /// </summary>
        internal static string MAP_COASTLINE {
            get {
                return ResourceManager.GetString("MAP_COASTLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consulate	 的本地化字符串。
        /// </summary>
        internal static string MAP_CONSULATE {
            get {
                return ResourceManager.GetString("MAP_CONSULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emerald Plains 的本地化字符串。
        /// </summary>
        internal static string MAP_EMERALD_PLAINS {
            get {
                return ResourceManager.GetString("MAP_EMERALD_PLAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favela	 的本地化字符串。
        /// </summary>
        internal static string MAP_FAVELA {
            get {
                return ResourceManager.GetString("MAP_FAVELA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fortress	 的本地化字符串。
        /// </summary>
        internal static string MAP_FORTRESS {
            get {
                return ResourceManager.GetString("MAP_FORTRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hereford Base 的本地化字符串。
        /// </summary>
        internal static string MAP_HEREFORD_BASE {
            get {
                return ResourceManager.GetString("MAP_HEREFORD_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 House	 的本地化字符串。
        /// </summary>
        internal static string MAP_HOUSE {
            get {
                return ResourceManager.GetString("MAP_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kafe	 的本地化字符串。
        /// </summary>
        internal static string MAP_KAFE_DOSTOYEVSKY {
            get {
                return ResourceManager.GetString("MAP_KAFE_DOSTOYEVSKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kanal	 的本地化字符串。
        /// </summary>
        internal static string MAP_KANAL {
            get {
                return ResourceManager.GetString("MAP_KANAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nighthaven Labs 的本地化字符串。
        /// </summary>
        internal static string MAP_NIGHTHAVEN_LABS {
            get {
                return ResourceManager.GetString("MAP_NIGHTHAVEN_LABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oregon	 的本地化字符串。
        /// </summary>
        internal static string MAP_OREGON {
            get {
                return ResourceManager.GetString("MAP_OREGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outback	 的本地化字符串。
        /// </summary>
        internal static string MAP_OUTBACK {
            get {
                return ResourceManager.GetString("MAP_OUTBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plane	 的本地化字符串。
        /// </summary>
        internal static string MAP_PRESIDENTIAL_PLANE {
            get {
                return ResourceManager.GetString("MAP_PRESIDENTIAL_PLANE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skyscraper 的本地化字符串。
        /// </summary>
        internal static string MAP_SKYSCRAPER {
            get {
                return ResourceManager.GetString("MAP_SKYSCRAPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stadium Bravo 的本地化字符串。
        /// </summary>
        internal static string MAP_STADIUM_BRAVO {
            get {
                return ResourceManager.GetString("MAP_STADIUM_BRAVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme Park	 的本地化字符串。
        /// </summary>
        internal static string MAP_THEME_PARK {
            get {
                return ResourceManager.GetString("MAP_THEME_PARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tower	 的本地化字符串。
        /// </summary>
        internal static string MAP_TOWER {
            get {
                return ResourceManager.GetString("MAP_TOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown	 的本地化字符串。
        /// </summary>
        internal static string MAP_UNKNOWN {
            get {
                return ResourceManager.GetString("MAP_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Villa	 的本地化字符串。
        /// </summary>
        internal static string MAP_VILLA {
            get {
                return ResourceManager.GetString("MAP_VILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yacht	 的本地化字符串。
        /// </summary>
        internal static string MAP_YACHT {
            get {
                return ResourceManager.GetString("MAP_YACHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading your local records... 的本地化字符串。
        /// </summary>
        internal static string MSG_READING_REC_DATA {
            get {
                return ResourceManager.GetString("MSG_READING_REC_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Takes longer when first run or new version. 的本地化字符串。
        /// </summary>
        internal static string MSG_REC_TEMP {
            get {
                return ResourceManager.GetString("MSG_REC_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A background task failed. It is not fatal, but worth mentioning. 的本地化字符串。
        /// </summary>
        internal static string TASK_EXCEPTION {
            get {
                return ResourceManager.GetString("TASK_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Task Failure 的本地化字符串。
        /// </summary>
        internal static string TASK_EXCEPTION_TITLE {
            get {
                return ResourceManager.GetString("TASK_EXCEPTION_TITLE", resourceCulture);
            }
        }
    }
}
